#
/control/verbose 2
/run/verbose 1
#
/hepd/setWorldSize 55 75 150 cm

/hepd/ActivateSatellite true
/hepd/SatelliteConfiguration Config1
/hepd/Satellite/BlanketMaterialConfiguration mylar
/hepd/Satellite/WallMaterialConfiguration Aluminium

/hepd/ActivateHEPDBox true
/hepd/HEPDBoxConfiguration Config4
/hepd/HEPDBox/BlanketMaterialConfiguration mylar
/hepd/HEPDBox/WallTwoMaterialConfiguration Aluminium HCAluminium

/hepd/ActivateTracker true
/hepd/TrackerConfiguration Config4
/hepd/Tracker/SiliconMaterialConfiguration Silicon
/hepd/Tracker/KaptonMaterialConfiguration Kapton
/hepd/Tracker/CarbonFiberMaterialConfiguration CarbonFiber

#/hepd/ActivateScintillator true
#/hepd/ScintillatorConfiguration Config4
#/hepd/Scintillator/ScintillatorMaterialConfiguration Scintillator
#/hepd/Scintillator/PoronMaterialConfiguration Poron 
#/hepd/Scintillator/CarbonFiberMaterialConfiguration CarbonFiber

/hepd/ActivateCalo true
/hepd/CaloConfiguration Config6
/hepd/Calorimeter/CalorimeterTwoMaterialConfiguration Scintillator LYSO
/hepd/Calorimeter/VetoMaterialConfiguration Scintillator
/hepd/Calorimeter/PoronMaterialConfiguration Poron
/hepd/Calorimeter/CarbonFiberMaterialConfiguration CarbonFiber

#
/hepd/phys/addPhysics  emstandard_opt4
/run/initialize
#/hepd/ScintillatorSD/useBirksLaw false
#/hepd/CalorimeterSD/useBirksLaw false
#/hepd/VetoSD/useBirksLaw false
#
# Use this open statement to create an OpenGL view:
/vis/open OGL 600x600-0+0

# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Draw coordinate axes:
/vis/scene/add/axes 0 0 0 60 cm
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
/hepd/gun/setDefault
/hepd/gun/random
/hepd/gun/toCenter
/hepd/gun/particle e-
/hepd/gun/energy 30 MeV
#

/hepd/producer/SetRootFile Test.root HEPD

#/run/beamOn 1

#/hepd/producer/StoreRootFile
